[project]
authors = ["Sarah Schwartz"]
entry = "main.sw"
license = "Apache-2.0"
name = "fuelnaut"

[dependencies]
sway_libs = { git = "https://github.com/FuelLabs/sway-libs", tag = "v0.22.0" }
standards = { git = "https://github.com/FuelLabs/sway-standards", tag = "v0.5.0" }
