[project]
authors = ["Sarah Schwartz"]
entry = "main.sw"
license = "Apache-2.0"
name = "fuelnaut"

[dependencies]
src5 = { git = "https://github.com/FuelLabs/sway-standards", tag = "v0.3.3" }
ownership = { git = "https://github.com/FuelLabs/sway-libs", tag = "v0.18.0" }
bytecode = { git = "https://github.com/FuelLabs/sway-libs", tag = "v0.19.0" }